server.port=7005
spring.application.name=faculty-service

# Import from Config Server (with authentication)
spring.config.import=configserver:http://admin:admin@localhost:8888/

spring.cloud.config.username=admin
spring.cloud.config.password=admin
spring.cloud.config.fail-fast=false

# Eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
