server.port=7004
spring.application.name=faculty-service

# Config Server
spring.config.import=configserver:http://localhost:8888

# Config Server authentication (if needed)
spring.cloud.config.username=admin
spring.cloud.config.password=admin

# Eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
