spring.application.name=configurationserver
server.port=8888

# Use LOCAL FILES instead of GitHub
spring.profiles.active=native

spring.security.user.name=admin
spring.security.user.password=admin

# Correct path to your local config folder (NO BACKSLASHES)
spring.cloud.config.server.native.search-locations=file:///D:/University_Management/University_Management/configurationserver/configurationserver/src/main/resources/config/
