spring.application.name=apigateway
server.port=8080

# Eureka client settings
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.server.enableReplication=false
eureka.client.service-url.defaultZone=http://discoveryservice:discoveryservice@localhost:8761/eureka/
spring.cloud.gateway.server.webflux.default-filters=PreserveHostHeader